### PR TITLE
Multithreaded chunk unload for both unloading and render distance "stuff"

### PR DESCRIPTION
**Pull request by Redhacker1**
Note: I have not really touched chunk generation with the exception of increasing the load radius to 5 and the chunk width and length to 16 for testing purposes. Chunk loading speed is about the same, though you do not have large lag spikes walking in and out of chunks. It also *might* help with block placement a little bit, but not much if at all, at least I am not seeing an improvement. 

I have experienced one or two crashes and odd spikes of chunk unloading, that being said those have been fairly rare. I am tracking down what causes the former currently. I am also unsure if that crash was due to something that was not mine.

I have placed a mutex on everything that handles the "loaded_chunks" array? dictionary? not sure what it is, I think it is a multi-dimensional array but it does not look like it at the same time. (the problem with dynamically typed languages without great IDE's that you cannot tell what the variable is unless you are in the mindset of the person who made it) grabbing the chunk itself and manipulating it is not mutexed and I would expect that to be handled in the chunk itself if it was a huge concern.

### CODE REVIEW

**Comment by Redhacker1** [comment]
Removed a small not correctly working optimization, that should fix most of the issues I was experiencing.

**Comment by xen-42** [comment]
Seems good to me.

**Comment by Redhacker1** [comment]
Also worked on porting most of the chunk generation to C#, still broken AF but a MC sized chunk (16x255x16) is doable. 
here is an image, if you are wanting to learn C# and want an example you should understand this is (for the most part) a straightforward port of the same logic.

 The biggest intentional difference being actually my code since who knew a foreach() loop did not like you editing the values inside it while it was running through the loop. There is also the fact that all blocks are classes because I could not think of a better solution that lines up with C# standards (everything is strongly typed, there cannot be an array with both an integer and a character in their native formats)

image

**Comment by xen-42** [comment]
How big of a performance increase does C# give?

**Comment by Redhacker1** [comment]
Oh well, I would say it slashes chunk generation time by about 50% from 18.7 or so seconds to ~10 seconds with equivalent configuration settings (the chunk size and the load radius provided by default). Most of the stuttering is gone in-game, the breaking block/(I would assume placing block) stutter is mostly gone though is notably still slightly there. Memory usage is also decreased ~50%, from 1.5GB to 715MB.

**Pull request merged**
