### PR TITLE
(PARTIAL!) Working nocollison tag

### PR DESCRIPTION
**Pull request by Redhacker1**
This is ported from the C# branch

I cannot tell if there is a performance hit, though I am effectively creating two meshes: one for the visual representation and one for the collision. I will probably have to figure out how to do collision channels in Godot and move the visual one to a different channel and set the line trace you use so that the line trace detects that new channel. If you know how to do that feel free to make the required changes here and then merge them.

Currently, the blocks that are marked with the no collision tag will not interact with the player at all, that includes destroying and replacing them, once they are generated they are there and there is nothing the player can do, hence why I said partial.

### CODE REVIEW

**Comment by xen-42** [comment]
Makes sense, much better than using the create_trimesh method (not supposed to be used outside of testing)

**Comment by Redhacker1** [comment]
I am using that at the moment (the collision is an invisible mesh) that being said I am pretty open to looking for alternatives, the thing is no matter what you do creating collisions at runtime is not cheap, and creating a Complex collision mesh is, even more, the case. Unfortunately, you have no choice in a game like Minecraft but to do such a thing. Terrain generation in general is pretty bad in this regard.

**Comment by xen-42** [comment]
Rather than creating 2 meshes with one that also has the non-collision meshes, wouldnt it be quicker to create 2 meshes where the first one contains blocks which have collisions, and the second mesh has blocks that do not collide? It might also be good to still create a collision mesh for the non-collision blocks, to allow raycasts to collide with them, just make sure its on a layer that doesnt collide with the player. Currently the player can't destroy flowers and stuff.

**Comment by Redhacker1** [comment]
I have it figured out in the C# branch and will port and push eventually

**Pull request merged**
